export interface Word {
  id: string
  hanzi: string
  pinyin: string
  hskLevel: number
  meaningEn: string
  meaningMn: string
  audioUrl: string
}

export const words: Word[] = [
  { id: "ayi", hanzi: "阿姨", pinyin: "āyí", hskLevel: 3, meaningEn: "aunt", meaningMn: "эгч, авга эх", audioUrl: "/audio/ayi.mp3" },
  { id: "a", hanzi: "啊", pinyin: "a", hskLevel: 3, meaningEn: "ah", meaningMn: "аа, ий (аялга)", audioUrl: "/audio/a.mp3" },
  { id: "ai", hanzi: "矮", pinyin: "ǎi", hskLevel: 3, meaningEn: "short (height)", meaningMn: "намхан", audioUrl: "/audio/ai.mp3" },
  { id: "aihao", hanzi: "爱好", pinyin: "àihào", hskLevel: 3, meaningEn: "hobby", meaningMn: "хобби, дуртай зүйл", audioUrl: "/audio/aihao.mp3" },
  { id: "anjing", hanzi: "安静", pinyin: "ānjìng", hskLevel: 3, meaningEn: "quiet", meaningMn: "чимээгүй", audioUrl: "/audio/anjing.mp3" },
  { id: "ba", hanzi: "把", pinyin: "bǎ", hskLevel: 3, meaningEn: "hold, (particle)", meaningMn: "барих, авах (тусгаарлагч)", audioUrl: "/audio/ba.mp3" },
  { id: "ban-class", hanzi: "班", pinyin: "bān", hskLevel: 3, meaningEn: "class", meaningMn: "анги", audioUrl: "/audio/ban.mp3" },
  { id: "ban-move", hanzi: "搬", pinyin: "bān", hskLevel: 3, meaningEn: "move", meaningMn: "нүүх, зөөх", audioUrl: "/audio/ban2.mp3" },
  { id: "ban-half", hanzi: "半", pinyin: "bàn", hskLevel: 3, meaningEn: "half", meaningMn: "хагас", audioUrl: "/audio/ban3.mp3" },
  { id: "banfa", hanzi: "办法", pinyin: "bànfǎ", hskLevel: 3, meaningEn: "way, method", meaningMn: "арга", audioUrl: "/audio/banfa.mp3" },
  { id: "bangongshi", hanzi: "办公室", pinyin: "bàngōngshì", hskLevel: 3, meaningEn: "office", meaningMn: "оффис", audioUrl: "/audio/bangongshi.mp3" },
  { id: "bangmang", hanzi: "帮忙", pinyin: "bāngmáng", hskLevel: 3, meaningEn: "help", meaningMn: "туслах", audioUrl: "/audio/bangmang.mp3" },
  { id: "bao", hanzi: "包", pinyin: "bāo", hskLevel: 3, meaningEn: "bag, package", meaningMn: "уут, багц", audioUrl: "/audio/bao.mp3" },
  { id: "bao-full", hanzi: "饱", pinyin: "bǎo", hskLevel: 3, meaningEn: "full (after eating)", meaningMn: "цатгалан", audioUrl: "/audio/bao2.mp3" },
  { id: "beifang", hanzi: "北方", pinyin: "běifāng", hskLevel: 3, meaningEn: "north", meaningMn: "хойд зүг", audioUrl: "/audio/beifang.mp3" },
  { id: "bei", hanzi: "被", pinyin: "bèi", hskLevel: 3, meaningEn: "by (passive marker)", meaningMn: "...д (идэвхгүй байдал)", audioUrl: "/audio/bei.mp3" },
  { id: "bizi", hanzi: "鼻子", pinyin: "bízi", hskLevel: 3, meaningEn: "nose", meaningMn: "хамар", audioUrl: "/audio/bizi.mp3" },
  { id: "bijiao", hanzi: "比较", pinyin: "bǐjiào", hskLevel: 3, meaningEn: "compare", meaningMn: "харьцуулах", audioUrl: "/audio/bijiao.mp3" },
  { id: "bisai", hanzi: "比赛", pinyin: "bǐsài", hskLevel: 3, meaningEn: "match, competition", meaningMn: "тэмцээн", audioUrl: "/audio/bisai.mp3" },
  { id: "bijiben", hanzi: "笔记本", pinyin: "bǐjìběn", hskLevel: 3, meaningEn: "notebook", meaningMn: "дэвтэр", audioUrl: "/audio/bijiben.mp3" },
  { id: "bixu", hanzi: "必须", pinyin: "bìxū", hskLevel: 3, meaningEn: "must", meaningMn: "заавал", audioUrl: "/audio/bixu.mp3" },
  { id: "bianhua", hanzi: "变化", pinyin: "biànhuà", hskLevel: 3, meaningEn: "change", meaningMn: "өөрчлөлт", audioUrl: "/audio/bianhua.mp3" },
  { id: "bieren", hanzi: "别人", pinyin: "biéren", hskLevel: 3, meaningEn: "others", meaningMn: "бусад хүн", audioUrl: "/audio/bieren.mp3" },
  { id: "bingxiang", hanzi: "冰箱", pinyin: "bīngxiāng", hskLevel: 3, meaningEn: "refrigerator", meaningMn: "хөргөгч", audioUrl: "/audio/bingxiang.mp3" },
  { id: "caidan", hanzi: "菜单", pinyin: "càidān", hskLevel: 3, meaningEn: "menu", meaningMn: "цэс", audioUrl: "/audio/caidan.mp3" },
  { id: "canjia", hanzi: "参加", pinyin: "cānjiā", hskLevel: 3, meaningEn: "participate in", meaningMn: "оролцох", audioUrl: "/audio/canjia.mp3" },
  { id: "cao", hanzi: "草", pinyin: "cǎo", hskLevel: 3, meaningEn: "grass", meaningMn: "өвс", audioUrl: "/audio/cao.mp3" },
  { id: "ceng", hanzi: "层", pinyin: "céng", hskLevel: 3, meaningEn: "floor, layer", meaningMn: "давхар", audioUrl: "/audio/ceng.mp3" },
  { id: "cha", hanzi: "差", pinyin: "chà", hskLevel: 3, meaningEn: "bad, poor", meaningMn: "муу", audioUrl: "/audio/cha.mp3" },
  { id: "chaoshi", hanzi: "超市", pinyin: "chāoshì", hskLevel: 3, meaningEn: "supermarket", meaningMn: "супермаркет", audioUrl: "/audio/chaoshi.mp3" },
  { id: "chenshan", hanzi: "衬衫", pinyin: "chènshān", hskLevel: 3, meaningEn: "shirt", meaningMn: "цамц", audioUrl: "/audio/chenshan.mp3" },
  { id: "chengji", hanzi: "成绩", pinyin: "chéngjì", hskLevel: 3, meaningEn: "achievement, score", meaningMn: "гүйцэтгэл, дүн", audioUrl: "/audio/chengji.mp3" },
  { id: "chengshi", hanzi: "城市", pinyin: "chéngshì", hskLevel: 3, meaningEn: "city", meaningMn: "хот", audioUrl: "/audio/chengshi.mp3" },
  { id: "chidao", hanzi: "迟到", pinyin: "chídào", hskLevel: 3, meaningEn: "late, tardy", meaningMn: "хоцрох", audioUrl: "/audio/chidao.mp3" },
  { id: "chule", hanzi: "除了", pinyin: "chúle", hskLevel: 3, meaningEn: "except, besides", meaningMn: "...аас бусад", audioUrl: "/audio/chule.mp3" },
  { id: "chuan", hanzi: "船", pinyin: "chuán", hskLevel: 3, meaningEn: "ship, boat", meaningMn: "хөлөг онгоц", audioUrl: "/audio/chuan.mp3" },
  { id: "chun", hanzi: "春", pinyin: "chūn", hskLevel: 3, meaningEn: "spring", meaningMn: "хавар", audioUrl: "/audio/chun.mp3" },
  { id: "cidian", hanzi: "词典", pinyin: "cídiǎn", hskLevel: 3, meaningEn: "dictionary", meaningMn: "толь бичиг", audioUrl: "/audio/cidian.mp3" },
  { id: "congming", hanzi: "聪明", pinyin: "cōngming", hskLevel: 3, meaningEn: "clever", meaningMn: "ухаалаг", audioUrl: "/audio/congming.mp3" },
  { id: "dasao", hanzi: "打扫", pinyin: "dǎsǎo", hskLevel: 3, meaningEn: "clean, sweep", meaningMn: "цэвэрлэх", audioUrl: "/audio/dasao.mp3" },
  { id: "dasuan", hanzi: "打算", pinyin: "dǎsuàn", hskLevel: 3, meaningEn: "plan, intend", meaningMn: "төлөвлөх", audioUrl: "/audio/dasuan.mp3" },
  { id: "dai", hanzi: "带", pinyin: "dài", hskLevel: 3, meaningEn: "bring, take", meaningMn: "авчрах, дагуулах", audioUrl: "/audio/dai.mp3" },
  { id: "danxin", hanzi: "担心", pinyin: "dānxīn", hskLevel: 3, meaningEn: "worry", meaningMn: "санаа зовох", audioUrl: "/audio/danxin.mp3" },
  { id: "dangao", hanzi: "蛋糕", pinyin: "dàngāo", hskLevel: 3, meaningEn: "cake", meaningMn: "бялуу", audioUrl: "/audio/dangao.mp3" },
  { id: "dangran", hanzi: "当然", pinyin: "dāngrán", hskLevel: 3, meaningEn: "of course", meaningMn: "мэдээж", audioUrl: "/audio/dangran.mp3" },
  { id: "de-particle", hanzi: "地", pinyin: "de", hskLevel: 3, meaningEn: "(adverbial particle)", meaningMn: "(дайвар үгийн тусгаарлагч)", audioUrl: "/audio/de.mp3" },
  { id: "deng", hanzi: "灯", pinyin: "dēng", hskLevel: 3, meaningEn: "lamp, light", meaningMn: "гэрэл, чийдэн", audioUrl: "/audio/deng.mp3" },
  { id: "difang", hanzi: "地方", pinyin: "dìfang", hskLevel: 3, meaningEn: "place", meaningMn: "газар", audioUrl: "/audio/difang.mp3" },
  { id: "ditie", hanzi: "地铁", pinyin: "dìtiě", hskLevel: 3, meaningEn: "metro, subway", meaningMn: "метро", audioUrl: "/audio/ditie.mp3" },
  { id: "ditu", hanzi: "地图", pinyin: "dìtú", hskLevel: 3, meaningEn: "map", meaningMn: "газрын зураг", audioUrl: "/audio/ditu.mp3" },
  { id: "dianti", hanzi: "电梯", pinyin: "diàntī", hskLevel: 3, meaningEn: "elevator", meaningMn: "лифт", audioUrl: "/audio/dianti.mp3" },
  { id: "dianziyoujian", hanzi: "电子邮件", pinyin: "diànzǐyóujiàn", hskLevel: 3, meaningEn: "email", meaningMn: "и-мэйл", audioUrl: "/audio/dianziyoujian.mp3" },
  { id: "dong-east", hanzi: "东", pinyin: "dōng", hskLevel: 3, meaningEn: "east", meaningMn: "зүүн зүг", audioUrl: "/audio/dong.mp3" },
  { id: "dong-winter", hanzi: "冬", pinyin: "dōng", hskLevel: 3, meaningEn: "winter", meaningMn: "өвөл", audioUrl: "/audio/dong2.mp3" },
  { id: "dongwu", hanzi: "动物", pinyin: "dòngwù", hskLevel: 3, meaningEn: "animal", meaningMn: "амьтан", audioUrl: "/audio/dongwu.mp3" },
  { id: "duan", hanzi: "短", pinyin: "duǎn", hskLevel: 3, meaningEn: "short (length)", meaningMn: "богино", audioUrl: "/audio/duan.mp3" },
  { id: "duan-paragraph", hanzi: "段", pinyin: "duàn", hskLevel: 3, meaningEn: "paragraph, section", meaningMn: "хэсэг, параграф", audioUrl: "/audio/duan2.mp3" },
  { id: "duanlian", hanzi: "锻炼", pinyin: "duànliàn", hskLevel: 3, meaningEn: "exercise", meaningMn: "дасгал хийх", audioUrl: "/audio/duanlian.mp3" },
  { id: "duome", hanzi: "多么", pinyin: "duōme", hskLevel: 3, meaningEn: "how, such", meaningMn: "ямар их", audioUrl: "/audio/duome.mp3" },
  { id: "e", hanzi: "饿", pinyin: "è", hskLevel: 3, meaningEn: "hungry", meaningMn: "өлсөх", audioUrl: "/audio/e.mp3" },
  { id: "budan-erqie", hanzi: "不但……而且……", pinyin: "búdàn...érqiě...", hskLevel: 3, meaningEn: "not only...but also...", meaningMn: "зөвхөн...төдийгүй...", audioUrl: "/audio/budan-erqie.mp3" },
  { id: "erduo", hanzi: "耳朵", pinyin: "ěrduo", hskLevel: 3, meaningEn: "ear", meaningMn: "чих", audioUrl: "/audio/erduo.mp3" },
  { id: "fa", hanzi: "发", pinyin: "fā", hskLevel: 3, meaningEn: "send", meaningMn: "илгээх", audioUrl: "/audio/fa.mp3" },
  { id: "fashao", hanzi: "发烧", pinyin: "fāshāo", hskLevel: 3, meaningEn: "have a fever", meaningMn: "халуурах", audioUrl: "/audio/fashao.mp3" },
  { id: "faxian", hanzi: "发现", pinyin: "fāxiàn", hskLevel: 3, meaningEn: "discover, find", meaningMn: "нээх, олох", audioUrl: "/audio/faxian.mp3" },
  { id: "fangbian", hanzi: "方便", pinyin: "fāngbiàn", hskLevel: 3, meaningEn: "convenient", meaningMn: "тохиромжтой", audioUrl: "/audio/fangbian.mp3" },
  { id: "fang", hanzi: "放", pinyin: "fàng", hskLevel: 3, meaningEn: "put, place", meaningMn: "тавих", audioUrl: "/audio/fang.mp3" },
  { id: "fangxin", hanzi: "放心", pinyin: "fàngxīn", hskLevel: 3, meaningEn: "relax, don't worry", meaningMn: "санаа амар байх", audioUrl: "/audio/fangxin.mp3" },
  { id: "fen", hanzi: "分", pinyin: "fēn", hskLevel: 3, meaningEn: "minute", meaningMn: "минут", audioUrl: "/audio/fen.mp3" },
  { id: "fujin", hanzi: "附近", pinyin: "fùjìn", hskLevel: 3, meaningEn: "nearby", meaningMn: "ойролцоо", audioUrl: "/audio/fujin.mp3" },
  { id: "fuxi", hanzi: "复习", pinyin: "fùxí", hskLevel: 3, meaningEn: "review", meaningMn: "давтах", audioUrl: "/audio/fuxi.mp3" },
  { id: "ganjing", hanzi: "干净", pinyin: "gānjìng", hskLevel: 3, meaningEn: "clean", meaningMn: "цэвэр", audioUrl: "/audio/ganjing.mp3" },
  { id: "ganxingqu", hanzi: "感兴趣", pinyin: "gǎnxìngqù", hskLevel: 3, meaningEn: "be interested in", meaningMn: "сонирхох", audioUrl: "/audio/ganxingqu.mp3" },
  { id: "ganmao", hanzi: "感冒", pinyin: "gǎnmào", hskLevel: 3, meaningEn: "cold, flu", meaningMn: "томуу хүрэх", audioUrl: "/audio/ganmao.mp3" },
  { id: "gangcai", hanzi: "刚才", pinyin: "gāngcái", hskLevel: 3, meaningEn: "just now", meaningMn: "саяхан", audioUrl: "/audio/gangcai.mp3" },
  { id: "gezi", hanzi: "个子", pinyin: "gèzi", hskLevel: 3, meaningEn: "height, stature", meaningMn: "өндөр нам", audioUrl: "/audio/gezi.mp3" },
  { id: "gen", hanzi: "跟", pinyin: "gēn", hskLevel: 3, meaningEn: "with, follow", meaningMn: "...тай хамт", audioUrl: "/audio/gen.mp3" },
  { id: "genju", hanzi: "根据", pinyin: "gēnjù", hskLevel: 3, meaningEn: "according to", meaningMn: "...д үндэслэн", audioUrl: "/audio/genju.mp3" },
  { id: "geng", hanzi: "更", pinyin: "gèng", hskLevel: 3, meaningEn: "even more", meaningMn: "илүү", audioUrl: "/audio/geng.mp3" },
  { id: "gongjin", hanzi: "公斤", pinyin: "gōngjīn", hskLevel: 3, meaningEn: "kilogram", meaningMn: "килограмм", audioUrl: "/audio/gongjin.mp3" },
  { id: "gongyuan", hanzi: "公园", pinyin: "gōngyuán", hskLevel: 3, meaningEn: "park", meaningMn: "цэцэрлэгт хүрээлэн", audioUrl: "/audio/gongyuan.mp3" },
  { id: "gushi", hanzi: "故事", pinyin: "gùshi", hskLevel: 3, meaningEn: "story", meaningMn: "үлгэр, түүх", audioUrl: "/audio/gushi.mp3" },
  { id: "guafeng", hanzi: "刮风", pinyin: "guāfēng", hskLevel: 3, meaningEn: "windy", meaningMn: "салхи шуурах", audioUrl: "/audio/guafeng.mp3" },
  { id: "guan", hanzi: "关", pinyin: "guān", hskLevel: 3, meaningEn: "close, shut", meaningMn: "хаах", audioUrl: "/audio/guan.mp3" },
  { id: "guanxi", hanzi: "关系", pinyin: "guānxì", hskLevel: 3, meaningEn: "relationship", meaningMn: "харилцаа", audioUrl: "/audio/guanxi.mp3" },
  { id: "guanxin", hanzi: "关心", pinyin: "guānxīn", hskLevel: 3, meaningEn: "care for", meaningMn: "анхаарах, халамжлах", audioUrl: "/audio/guanxin.mp3" },
  { id: "guanyu", hanzi: "关于", pinyin: "guānyú", hskLevel: 3, meaningEn: "about, regarding", meaningMn: "...ийн тухай", audioUrl: "/audio/guanyu.mp3" },
  { id: "guojia", hanzi: "国家", pinyin: "guójiā", hskLevel: 3, meaningEn: "country", meaningMn: "улс орон", audioUrl: "/audio/guojia.mp3" },
  { id: "guoqu", hanzi: "过去", pinyin: "guòqù", hskLevel: 3, meaningEn: "past", meaningMn: "өнгөрсөн", audioUrl: "/audio/guoqu.mp3" },
  { id: "guo-verb", hanzi: "过", pinyin: "guò", hskLevel: 3, meaningEn: "pass, go through", meaningMn: "өнгөрөх", audioUrl: "/audio/guo.mp3" },
  { id: "haishi", hanzi: "还是", pinyin: "háishì", hskLevel: 3, meaningEn: "still, or", meaningMn: "эсвэл, гэсэн ч", audioUrl: "/audio/haishi.mp3" },
  { id: "haipa", hanzi: "害怕", pinyin: "hàipà", hskLevel: 3, meaningEn: "fear, afraid", meaningMn: "айх", audioUrl: "/audio/haipa.mp3" },
  { id: "heiban", hanzi: "黑板", pinyin: "hēibǎn", hskLevel: 3, meaningEn: "blackboard", meaningMn: "самбар", audioUrl: "/audio/heiban.mp3" },
  { id: "houlai", hanzi: "后来", pinyin: "hòulái", hskLevel: 3, meaningEn: "later, afterwards", meaningMn: "дараа нь", audioUrl: "/audio/houlai.mp3" },
  { id: "huzhao", hanzi: "护照", pinyin: "hùzhào", hskLevel: 3, meaningEn: "passport", meaningMn: "паспорт", audioUrl: "/audio/huzhao.mp3" },
  { id: "hua-spend", hanzi: "花", pinyin: "huā", hskLevel: 3, meaningEn: "spend", meaningMn: "зарцуулах", audioUrl: "/audio/hua.mp3" },
  { id: "hua-flower", hanzi: "花", pinyin: "huā", hskLevel: 3, meaningEn: "flower", meaningMn: "цэцэг", audioUrl: "/audio/hua2.mp3" },
  { id: "hua-painting", hanzi: "画", pinyin: "huà", hskLevel: 3, meaningEn: "painting, draw", meaningMn: "зураг, зурах", audioUrl: "/audio/hua3.mp3" },
  { id: "huai", hanzi: "坏", pinyin: "huài", hskLevel: 3, meaningEn: "bad, broken", meaningMn: "муу, эвдэрсэн", audioUrl: "/audio/huai.mp3" },
  { id: "huanying", hanzi: "欢迎", pinyin: "huānyíng", hskLevel: 3, meaningEn: "welcome", meaningMn: "тавтай морил", audioUrl: "/audio/huanying.mp3" },
  { id: "huan-return", hanzi: "还", pinyin: "huán", hskLevel: 3, meaningEn: "return", meaningMn: "буцааж өгөх", audioUrl: "/audio/huan.mp3" },
  { id: "huanjing", hanzi: "环境", pinyin: "huánjìng", hskLevel: 3, meaningEn: "environment", meaningMn: "орчин", audioUrl: "/audio/huanjing.mp3" },
  { id: "huan-change", hanzi: "换", pinyin: "huàn", hskLevel: 3, meaningEn: "change, exchange", meaningMn: "солих", audioUrl: "/audio/huan2.mp3" },
  { id: "huanghe", hanzi: "黄河", pinyin: "huánghé", hskLevel: 3, meaningEn: "Yellow River", meaningMn: "Шар мөрөн", audioUrl: "/audio/huanghe.mp3" },
  { id: "huida", hanzi: "回答", pinyin: "huídá", hskLevel: 3, meaningEn: "answer", meaningMn: "хариулах", audioUrl: "/audio/huida.mp3" },
  { id: "huiyi", hanzi: "会议", pinyin: "huìyì", hskLevel: 3, meaningEn: "meeting", meaningMn: "хурал", audioUrl: "/audio/huiyi.mp3" },
  { id: "huozhe", hanzi: "或者", pinyin: "huòzhě", hskLevel: 3, meaningEn: "or, perhaps", meaningMn: "эсвэл", audioUrl: "/audio/huozhe.mp3" },
  { id: "jihu", hanzi: "几乎", pinyin: "jīhū", hskLevel: 3, meaningEn: "almost", meaningMn: "бараг", audioUrl: "/audio/jihu.mp3" },
  { id: "jihui", hanzi: "机会", pinyin: "jīhuì", hskLevel: 3, meaningEn: "opportunity", meaningMn: "боломж", audioUrl: "/audio/jihui.mp3" },
  { id: "ji", hanzi: "极", pinyin: "jí", hskLevel: 3, meaningEn: "extremely", meaningMn: "маш их", audioUrl: "/audio/ji.mp3" },
  { id: "jide", hanzi: "记得", pinyin: "jìde", hskLevel: 3, meaningEn: "remember", meaningMn: "санах", audioUrl: "/audio/jide.mp3" },
  { id: "jijie", hanzi: "季节", pinyin: "jìjié", hskLevel: 3, meaningEn: "season", meaningMn: "улирал", audioUrl: "/audio/jijie.mp3" },
  { id: "jiancha", hanzi: "检查", pinyin: "jiǎnchá", hskLevel: 3, meaningEn: "inspect, check", meaningMn: "шалгах", audioUrl: "/audio/jiancha.mp3" },
  { id: "jiandan", hanzi: "简单", pinyin: "jiǎndān", hskLevel: 3, meaningEn: "simple", meaningMn: "энгийн", audioUrl: "/audio/jiandan.mp3" },
  { id: "jiankang", hanzi: "健康", pinyin: "jiànkāng", hskLevel: 3, meaningEn: "healthy", meaningMn: "эрүүл", audioUrl: "/audio/jiankang.mp3" },
  { id: "jianmian", hanzi: "见面", pinyin: "jiànmiàn", hskLevel: 3, meaningEn: "meet", meaningMn: "уулзах", audioUrl: "/audio/jianmian.mp3" },
  { id: "jiang", hanzi: "讲", pinyin: "jiǎng", hskLevel: 3, meaningEn: "speak, tell", meaningMn: "ярих", audioUrl: "/audio/jiang.mp3" },
  { id: "jiao-teach", hanzi: "教", pinyin: "jiāo", hskLevel: 3, meaningEn: "teach", meaningMn: "заах", audioUrl: "/audio/jiao.mp3" },
  { id: "jiao-horn", hanzi: "角", pinyin: "jiǎo", hskLevel: 3, meaningEn: "corner, horn", meaningMn: "булан, эвэр", audioUrl: "/audio/jiao2.mp3" },
  { id: "jiao-foot", hanzi: "脚", pinyin: "jiǎo", hskLevel: 3, meaningEn: "foot", meaningMn: "хөл", audioUrl: "/audio/jiao3.mp3" },
  { id: "jie", hanzi: "接", pinyin: "jiē", hskLevel: 3, meaningEn: "pick up, receive", meaningMn: "авах, угтах", audioUrl: "/audio/jie.mp3" },
  { id: "jiedao", hanzi: "街道", pinyin: "jiēdào", hskLevel: 3, meaningEn: "street", meaningMn: "гудамж", audioUrl: "/audio/jiedao.mp3" },
  { id: "jiehun", hanzi: "结婚", pinyin: "jiéhūn", hskLevel: 3, meaningEn: "marry", meaningMn: "гэрлэх", audioUrl: "/audio/jiehun.mp3" },
  { id: "jieshu", hanzi: "结束", pinyin: "jiéshù", hskLevel: 3, meaningEn: "end, finish", meaningMn: "дуусах", audioUrl: "/audio/jieshu.mp3" },
  { id: "jiemu", hanzi: "节目", pinyin: "jiémù", hskLevel: 3, meaningEn: "program, show", meaningMn: "нэвтрүүлэг", audioUrl: "/audio/jiemu.mp3" },
  { id: "jieri", hanzi: "节日", pinyin: "jiérì", hskLevel: 3, meaningEn: "festival, holiday", meaningMn: "баяр ёслол", audioUrl: "/audio/jieri.mp3" },
  { id: "jiejue", hanzi: "解决", pinyin: "jiějué", hskLevel: 3, meaningEn: "solve", meaningMn: "шийдвэрлэх", audioUrl: "/audio/jiejue.mp3" },
  { id: "jie-borrow", hanzi: "借", pinyin: "jiè", hskLevel: 3, meaningEn: "borrow", meaningMn: "зээлэх", audioUrl: "/audio/jie2.mp3" },
  { id: "jingchang", hanzi: "经常", pinyin: "jīngcháng", hskLevel: 3, meaningEn: "often", meaningMn: "байнга", audioUrl: "/audio/jingchang.mp3" },
  { id: "jingguo", hanzi: "经过", pinyin: "jīngguò", hskLevel: 3, meaningEn: "pass through, after", meaningMn: "дайрч өнгөрөх", audioUrl: "/audio/jingguo.mp3" },
  { id: "jingli", hanzi: "经理", pinyin: "jīnglǐ", hskLevel: 3, meaningEn: "manager", meaningMn: "менежер", audioUrl: "/audio/jingli.mp3" },
  { id: "jiu", hanzi: "久", pinyin: "jiǔ", hskLevel: 3, meaningEn: "long (time)", meaningMn: "удаан", audioUrl: "/audio/jiu.mp3" },
  { id: "jiu-old", hanzi: "旧", pinyin: "jiù", hskLevel: 3, meaningEn: "old, used", meaningMn: "хуучин", audioUrl: "/audio/jiu2.mp3" },
  { id: "juzi", hanzi: "句子", pinyin: "jùzi", hskLevel: 3, meaningEn: "sentence", meaningMn: "өгүүлбэр", audioUrl: "/audio/juzi.mp3" },
  { id: "jueding", hanzi: "决定", pinyin: "juédìng", hskLevel: 3, meaningEn: "decide, decision", meaningMn: "шийдэх", audioUrl: "/audio/jueding.mp3" },
  { id: "ke-thirsty", hanzi: "渴", pinyin: "kě", hskLevel: 3, meaningEn: "thirsty", meaningMn: "цангах", audioUrl: "/audio/ke.mp3" },
  { id: "keai", hanzi: "可爱", pinyin: "kě'ài", hskLevel: 3, meaningEn: "cute, lovely", meaningMn: "хөөрхөн", audioUrl: "/audio/keai.mp3" },
  { id: "ke-moment", hanzi: "刻", pinyin: "kè", hskLevel: 3, meaningEn: "quarter hour", meaningMn: "15 минут", audioUrl: "/audio/ke2.mp3" },
  { id: "keren", hanzi: "客人", pinyin: "kèrén", hskLevel: 3, meaningEn: "guest", meaningMn: "зочин", audioUrl: "/audio/keren.mp3" },
  { id: "kongtiao", hanzi: "空调", pinyin: "kōngtiáo", hskLevel: 3, meaningEn: "air conditioner", meaningMn: "агааржуулагч", audioUrl: "/audio/kongtiao.mp3" },
  { id: "kou", hanzi: "口", pinyin: "kǒu", hskLevel: 3, meaningEn: "mouth", meaningMn: "ам", audioUrl: "/audio/kou.mp3" },
  { id: "ku", hanzi: "哭", pinyin: "kū", hskLevel: 3, meaningEn: "cry", meaningMn: "уйлах", audioUrl: "/audio/ku.mp3" },
  { id: "kuzi", hanzi: "裤子", pinyin: "kùzi", hskLevel: 3, meaningEn: "trousers", meaningMn: "өмд", audioUrl: "/audio/kuzi.mp3" },
  { id: "kuaizi", hanzi: "筷子", pinyin: "kuàizi", hskLevel: 3, meaningEn: "chopsticks", meaningMn: "таяг", audioUrl: "/audio/kuaizi.mp3" },
  { id: "lan", hanzi: "蓝", pinyin: "lán", hskLevel: 3, meaningEn: "blue", meaningMn: "цэнхэр", audioUrl: "/audio/lan.mp3" },
  { id: "lao", hanzi: "老", pinyin: "lǎo", hskLevel: 3, meaningEn: "old", meaningMn: "хөгшин", audioUrl: "/audio/lao.mp3" },
  { id: "likai", hanzi: "离开", pinyin: "líkāi", hskLevel: 3, meaningEn: "leave", meaningMn: "явах, орхих", audioUrl: "/audio/likai.mp3" },
  { id: "liwu", hanzi: "礼物", pinyin: "lǐwù", hskLevel: 3, meaningEn: "gift", meaningMn: "бэлэг", audioUrl: "/audio/liwu.mp3" },
  { id: "lishi", hanzi: "历史", pinyin: "lìshǐ", hskLevel: 3, meaningEn: "history", meaningMn: "түүх", audioUrl: "/audio/lishi.mp3" },
  { id: "lian", hanzi: "脸", pinyin: "liǎn", hskLevel: 3, meaningEn: "face", meaningMn: "нүүр", audioUrl: "/audio/lian.mp3" },
  { id: "liaotian", hanzi: "聊天", pinyin: "liáotiān", hskLevel: 3, meaningEn: "chat", meaningMn: "яриа өрнүүлэх", audioUrl: "/audio/liaotian.mp3" },
  { id: "lianxi", hanzi: "练习", pinyin: "liànxí", hskLevel: 3, meaningEn: "practice", meaningMn: "дасгал хийх", audioUrl: "/audio/lianxi.mp3" },
  { id: "liang", hanzi: "辆", pinyin: "liàng", hskLevel: 3, meaningEn: "(measure word for vehicles)", meaningMn: "(тооны үг - машин)", audioUrl: "/audio/liang.mp3" },
  { id: "liaojie", hanzi: "了解", pinyin: "liǎojiě", hskLevel: 3, meaningEn: "understand", meaningMn: "ойлгох", audioUrl: "/audio/liaojie.mp3" },
  { id: "linju", hanzi: "邻居", pinyin: "línjū", hskLevel: 3, meaningEn: "neighbor", meaningMn: "хөрш", audioUrl: "/audio/linju.mp3" },
  { id: "liuxue", hanzi: "留学", pinyin: "liúxué", hskLevel: 3, meaningEn: "study abroad", meaningMn: "гадаадад суралцах", audioUrl: "/audio/liuxue.mp3" },
  { id: "lou", hanzi: "楼", pinyin: "lóu", hskLevel: 3, meaningEn: "floor, building", meaningMn: "давхар, барилга", audioUrl: "/audio/lou.mp3" },
  { id: "lv", hanzi: "绿", pinyin: "lǜ", hskLevel: 3, meaningEn: "green", meaningMn: "ногоон", audioUrl: "/audio/lv.mp3" },
  { id: "ma", hanzi: "马", pinyin: "mǎ", hskLevel: 3, meaningEn: "horse", meaningMn: "морь", audioUrl: "/audio/ma.mp3" },
  { id: "mashang", hanzi: "马上", pinyin: "mǎshàng", hskLevel: 3, meaningEn: "immediately", meaningMn: "даруй", audioUrl: "/audio/mashang.mp3" },
  { id: "manyi", hanzi: "满意", pinyin: "mǎnyì", hskLevel: 3, meaningEn: "satisfied", meaningMn: "сэтгэл хангалуун", audioUrl: "/audio/manyi.mp3" },
  { id: "maozi", hanzi: "帽子", pinyin: "màozi", hskLevel: 3, meaningEn: "hat", meaningMn: "малгай", audioUrl: "/audio/maozi.mp3" },
  { id: "mi", hanzi: "米", pinyin: "mǐ", hskLevel: 3, meaningEn: "rice, meter", meaningMn: "будаа, метр", audioUrl: "/audio/mi.mp3" },
  { id: "mianbao", hanzi: "面包", pinyin: "miànbāo", hskLevel: 3, meaningEn: "bread", meaningMn: "талх", audioUrl: "/audio/mianbao.mp3" },
  { id: "mingbai", hanzi: "明白", pinyin: "míngbai", hskLevel: 3, meaningEn: "understand, clear", meaningMn: "ойлгох", audioUrl: "/audio/mingbai.mp3" },
  { id: "na", hanzi: "拿", pinyin: "ná", hskLevel: 3, meaningEn: "take, hold", meaningMn: "авах, барих", audioUrl: "/audio/na.mp3" },
  { id: "nainai", hanzi: "奶奶", pinyin: "nǎinai", hskLevel: 3, meaningEn: "grandma", meaningMn: "эмээ", audioUrl: "/audio/nainai.mp3" },
  { id: "nan-south", hanzi: "南", pinyin: "nán", hskLevel: 3, meaningEn: "south", meaningMn: "өмнөд зүг", audioUrl: "/audio/nan.mp3" },
  { id: "nan-difficult", hanzi: "难", pinyin: "nán", hskLevel: 3, meaningEn: "difficult", meaningMn: "хэцүү", audioUrl: "/audio/nan2.mp3" },
  { id: "nanguo", hanzi: "难过", pinyin: "nánguò", hskLevel: 3, meaningEn: "sad", meaningMn: "гунигтай", audioUrl: "/audio/nanguo.mp3" },
  { id: "nianji", hanzi: "年级", pinyin: "niánjí", hskLevel: 3, meaningEn: "grade, year", meaningMn: "анги, жил", audioUrl: "/audio/nianji.mp3" },
  { id: "nianqing", hanzi: "年轻", pinyin: "niánqīng", hskLevel: 3, meaningEn: "young", meaningMn: "залуу", audioUrl: "/audio/nianqing.mp3" },
  { id: "niao", hanzi: "鸟", pinyin: "niǎo", hskLevel: 3, meaningEn: "bird", meaningMn: "шувуу", audioUrl: "/audio/niao.mp3" },
  { id: "nuli", hanzi: "努力", pinyin: "nǔlì", hskLevel: 3, meaningEn: "strive, work hard", meaningMn: "хичээх", audioUrl: "/audio/nuli.mp3" },
  { id: "pashan", hanzi: "爬山", pinyin: "páshān", hskLevel: 3, meaningEn: "mountain climbing", meaningMn: "уул авирах", audioUrl: "/audio/pashan.mp3" },
  { id: "panzi", hanzi: "盘子", pinyin: "pánzi", hskLevel: 3, meaningEn: "plate", meaningMn: "таваг", audioUrl: "/audio/panzi.mp3" },
  { id: "pang", hanzi: "胖", pinyin: "pàng", hskLevel: 3, meaningEn: "fat", meaningMn: "тарган", audioUrl: "/audio/pang.mp3" },
  { id: "pijiu", hanzi: "啤酒", pinyin: "píjiǔ", hskLevel: 3, meaningEn: "beer", meaningMn: "пиво", audioUrl: "/audio/pijiu.mp3" },
  { id: "pixie", hanzi: "皮鞋", pinyin: "píxié", hskLevel: 3, meaningEn: "leather shoes", meaningMn: "арьсан гутал", audioUrl: "/audio/pixie.mp3" },
  { id: "pingzi", hanzi: "瓶子", pinyin: "píngzi", hskLevel: 3, meaningEn: "bottle", meaningMn: "лонх", audioUrl: "/audio/pingzi.mp3" },
  { id: "qishi", hanzi: "其实", pinyin: "qíshí", hskLevel: 3, meaningEn: "actually", meaningMn: "үнэндээ", audioUrl: "/audio/qishi.mp3" },
  { id: "qita", hanzi: "其他", pinyin: "qítā", hskLevel: 3, meaningEn: "other", meaningMn: "бусад", audioUrl: "/audio/qita.mp3" },
  { id: "qi-ride", hanzi: "骑", pinyin: "qí", hskLevel: 3, meaningEn: "ride", meaningMn: "унах", audioUrl: "/audio/qi.mp3" },
  { id: "qiguai", hanzi: "奇怪", pinyin: "qíguài", hskLevel: 3, meaningEn: "strange", meaningMn: "хачирхалтай", audioUrl: "/audio/qiguai.mp3" },
  { id: "qilai", hanzi: "起来", pinyin: "qǐlái", hskLevel: 3, meaningEn: "get up", meaningMn: "босох", audioUrl: "/audio/qilai.mp3" },
  { id: "qifei", hanzi: "起飞", pinyin: "qǐfēi", hskLevel: 3, meaningEn: "take off", meaningMn: "нислэг хийх", audioUrl: "/audio/qifei.mp3" },
  { id: "qingchu", hanzi: "清楚", pinyin: "qīngchu", hskLevel: 3, meaningEn: "clear", meaningMn: "тодорхой", audioUrl: "/audio/qingchu.mp3" },
  { id: "qingjia", hanzi: "请假", pinyin: "qǐngjià", hskLevel: 3, meaningEn: "ask for leave", meaningMn: "чөлөө хүсэх", audioUrl: "/audio/qingjia.mp3" },
  { id: "qiu", hanzi: "秋", pinyin: "qiū", hskLevel: 3, meaningEn: "autumn", meaningMn: "намар", audioUrl: "/audio/qiu.mp3" },
  { id: "qunzi", hanzi: "裙子", pinyin: "qúnzi", hskLevel: 3, meaningEn: "skirt", meaningMn: "юбка", audioUrl: "/audio/qunzi.mp3" },
  { id: "ranhou", hanzi: "然后", pinyin: "ránhòu", hskLevel: 3, meaningEn: "then, afterwards", meaningMn: "дараа нь", audioUrl: "/audio/ranhou.mp3" },
  { id: "reqing", hanzi: "热情", pinyin: "rèqíng", hskLevel: 3, meaningEn: "enthusiasm", meaningMn: "урам зориг", audioUrl: "/audio/reqing.mp3" },
  { id: "renwei", hanzi: "认为", pinyin: "rènwéi", hskLevel: 3, meaningEn: "think, believe", meaningMn: "гэж үзэх", audioUrl: "/audio/renwei.mp3" },
  { id: "renzhen", hanzi: "认真", pinyin: "rènzhēn", hskLevel: 3, meaningEn: "earnest, serious", meaningMn: "хичээнгүй", audioUrl: "/audio/renzhen.mp3" },
  { id: "rongyi", hanzi: "容易", pinyin: "róngyì", hskLevel: 3, meaningEn: "easy", meaningMn: "хялбар", audioUrl: "/audio/rongyi.mp3" },
  { id: "ruguo", hanzi: "如果", pinyin: "rúguǒ", hskLevel: 3, meaningEn: "if", meaningMn: "хэрэв", audioUrl: "/audio/ruguo.mp3" },
  { id: "san", hanzi: "伞", pinyin: "sǎn", hskLevel: 3, meaningEn: "umbrella", meaningMn: "шүхэр", audioUrl: "/audio/san.mp3" },
  { id: "shangwang", hanzi: "上网", pinyin: "shàngwǎng", hskLevel: 3, meaningEn: "surf the internet", meaningMn: "интернэт хэрэглэх", audioUrl: "/audio/shangwang.mp3" },
  { id: "shengqi", hanzi: "生气", pinyin: "shēngqì", hskLevel: 3, meaningEn: "get angry", meaningMn: "уурлах", audioUrl: "/audio/shengqi.mp3" },
  { id: "shengyin", hanzi: "声音", pinyin: "shēngyīn", hskLevel: 3, meaningEn: "voice, sound", meaningMn: "дуу хоолой", audioUrl: "/audio/shengyin.mp3" },
  { id: "shi-try", hanzi: "试", pinyin: "shì", hskLevel: 3, meaningEn: "try", meaningMn: "туршиж үзэх", audioUrl: "/audio/shi.mp3" },
  { id: "shijie", hanzi: "世界", pinyin: "shìjiè", hskLevel: 3, meaningEn: "world", meaningMn: "дэлхий", audioUrl: "/audio/shijie.mp3" },
  { id: "shou", hanzi: "瘦", pinyin: "shòu", hskLevel: 3, meaningEn: "thin, slim", meaningMn: "туранхай", audioUrl: "/audio/shou.mp3" },
  { id: "shufu", hanzi: "舒服", pinyin: "shūfu", hskLevel: 3, meaningEn: "comfortable", meaningMn: "тав тухтай", audioUrl: "/audio/shufu.mp3" },
  { id: "shushu", hanzi: "叔叔", pinyin: "shūshu", hskLevel: 3, meaningEn: "uncle", meaningMn: "авга ах", audioUrl: "/audio/shushu.mp3" },
  { id: "shu", hanzi: "树", pinyin: "shù", hskLevel: 3, meaningEn: "tree", meaningMn: "мод", audioUrl: "/audio/shu.mp3" },
  { id: "shuxue", hanzi: "数学", pinyin: "shùxué", hskLevel: 3, meaningEn: "mathematics", meaningMn: "математик", audioUrl: "/audio/shuxue.mp3" },
  { id: "shuaya", hanzi: "刷牙", pinyin: "shuāyá", hskLevel: 3, meaningEn: "brush teeth", meaningMn: "шүд угаах", audioUrl: "/audio/shuaya.mp3" },
  { id: "shuang", hanzi: "双", pinyin: "shuāng", hskLevel: 3, meaningEn: "pair, double", meaningMn: "хос", audioUrl: "/audio/shuang.mp3" },
  { id: "shuiping", hanzi: "水平", pinyin: "shuǐpíng", hskLevel: 3, meaningEn: "level, standard", meaningMn: "түвшин", audioUrl: "/audio/shuiping.mp3" },
  { id: "siji", hanzi: "司机", pinyin: "sījī", hskLevel: 3, meaningEn: "driver", meaningMn: "жолооч", audioUrl: "/audio/siji.mp3" },
  { id: "taiyang", hanzi: "太阳", pinyin: "tàiyáng", hskLevel: 3, meaningEn: "sun", meaningMn: "нар", audioUrl: "/audio/taiyang.mp3" },
  { id: "tebie", hanzi: "特别", pinyin: "tèbié", hskLevel: 3, meaningEn: "especially", meaningMn: "ялангуяа", audioUrl: "/audio/tebie.mp3" },
  { id: "teng", hanzi: "疼", pinyin: "téng", hskLevel: 3, meaningEn: "hurt, pain", meaningMn: "өвдөх", audioUrl: "/audio/teng.mp3" },
  { id: "tigao", hanzi: "提高", pinyin: "tígāo", hskLevel: 3, meaningEn: "improve, increase", meaningMn: "дээшлүүлэх", audioUrl: "/audio/tigao.mp3" },
  { id: "tiyu", hanzi: "体育", pinyin: "tǐyù", hskLevel: 3, meaningEn: "sports", meaningMn: "спорт", audioUrl: "/audio/tiyu.mp3" },
  { id: "tian", hanzi: "甜", pinyin: "tián", hskLevel: 3, meaningEn: "sweet", meaningMn: "чихэрлэг", audioUrl: "/audio/tian.mp3" },
  { id: "tiao", hanzi: "条", pinyin: "tiáo", hskLevel: 3, meaningEn: "(measure word for long things)", meaningMn: "(тооны үг - урт зүйл)", audioUrl: "/audio/tiao.mp3" },
  { id: "tongshi", hanzi: "同事", pinyin: "tóngshì", hskLevel: 3, meaningEn: "colleague", meaningMn: "хамтрагч", audioUrl: "/audio/tongshi.mp3" },
  { id: "tongyi", hanzi: "同意", pinyin: "tóngyì", hskLevel: 3, meaningEn: "agree", meaningMn: "зөвшөөрөх", audioUrl: "/audio/tongyi.mp3" },
  { id: "toufa", hanzi: "头发", pinyin: "tóufa", hskLevel: 3, meaningEn: "hair", meaningMn: "үс", audioUrl: "/audio/toufa.mp3" },
  { id: "turan", hanzi: "突然", pinyin: "tūrán", hskLevel: 3, meaningEn: "suddenly", meaningMn: "гэнэт", audioUrl: "/audio/turan.mp3" },
  { id: "tushuguan", hanzi: "图书馆", pinyin: "túshūguǎn", hskLevel: 3, meaningEn: "library", meaningMn: "номын сан", audioUrl: "/audio/tushuguan.mp3" },
  { id: "tui", hanzi: "腿", pinyin: "tuǐ", hskLevel: 3, meaningEn: "leg", meaningMn: "хөл (гуя)", audioUrl: "/audio/tui.mp3" },
  { id: "wancheng", hanzi: "完成", pinyin: "wánchéng", hskLevel: 3, meaningEn: "complete", meaningMn: "гүйцэтгэх", audioUrl: "/audio/wancheng.mp3" },
  { id: "wan", hanzi: "碗", pinyin: "wǎn", hskLevel: 3, meaningEn: "bowl", meaningMn: "аяга", audioUrl: "/audio/wan.mp3" },
  { id: "wan-10k", hanzi: "万", pinyin: "wàn", hskLevel: 3, meaningEn: "ten thousand", meaningMn: "арван мянга", audioUrl: "/audio/wan2.mp3" },
  { id: "wangji", hanzi: "忘记", pinyin: "wàngjì", hskLevel: 3, meaningEn: "forget", meaningMn: "мартах", audioUrl: "/audio/wangji.mp3" },
  { id: "wei-for", hanzi: "为", pinyin: "wèi", hskLevel: 3, meaningEn: "for", meaningMn: "...ын тулд", audioUrl: "/audio/wei.mp3" },
  { id: "weile", hanzi: "为了", pinyin: "wèile", hskLevel: 3, meaningEn: "in order to", meaningMn: "...ын тулд", audioUrl: "/audio/weile.mp3" },
  { id: "wei-position", hanzi: "位", pinyin: "wèi", hskLevel: 3, meaningEn: "(polite measure word for people)", meaningMn: "(хүнийг тооцох тооны үг)", audioUrl: "/audio/wei2.mp3" },
  { id: "wenhua", hanzi: "文化", pinyin: "wénhuà", hskLevel: 3, meaningEn: "culture", meaningMn: "соёл", audioUrl: "/audio/wenhua.mp3" },
  { id: "xi", hanzi: "西", pinyin: "xī", hskLevel: 3, meaningEn: "west", meaningMn: "баруун зүг", audioUrl: "/audio/xi.mp3" },
  { id: "xiguan", hanzi: "习惯", pinyin: "xíguàn", hskLevel: 3, meaningEn: "habit", meaningMn: "дадал", audioUrl: "/audio/xiguan.mp3" },
  { id: "xishoujian", hanzi: "洗手间", pinyin: "xǐshǒujiān", hskLevel: 3, meaningEn: "restroom", meaningMn: "ариун цэврийн өрөө", audioUrl: "/audio/xishoujian.mp3" },
  { id: "xizao", hanzi: "洗澡", pinyin: "xǐzǎo", hskLevel: 3, meaningEn: "take a shower", meaningMn: "усанд орох", audioUrl: "/audio/xizao.mp3" },
  { id: "xia", hanzi: "夏", pinyin: "xià", hskLevel: 3, meaningEn: "summer", meaningMn: "зун", audioUrl: "/audio/xia.mp3" },
  { id: "xian", hanzi: "先", pinyin: "xiān", hskLevel: 3, meaningEn: "first", meaningMn: "эхлээд", audioUrl: "/audio/xian.mp3" },
  { id: "xiangjiao", hanzi: "香蕉", pinyin: "xiāngjiāo", hskLevel: 3, meaningEn: "banana", meaningMn: "гадил жимс", audioUrl: "/audio/xiangjiao.mp3" },
  { id: "xiangxin", hanzi: "相信", pinyin: "xiāngxìn", hskLevel: 3, meaningEn: "believe", meaningMn: "итгэх", audioUrl: "/audio/xiangxin.mp3" },
  { id: "xiang-towards", hanzi: "向", pinyin: "xiàng", hskLevel: 3, meaningEn: "towards", meaningMn: "...руу", audioUrl: "/audio/xiang.mp3" },
  { id: "xiang-like", hanzi: "像", pinyin: "xiàng", hskLevel: 3, meaningEn: "resemble, like", meaningMn: "адилхан", audioUrl: "/audio/xiang2.mp3" },
  { id: "xiaoxin", hanzi: "小心", pinyin: "xiǎoxīn", hskLevel: 3, meaningEn: "be careful", meaningMn: "болгоомжтой байх", audioUrl: "/audio/xiaoxin.mp3" },
  { id: "xiaozhang", hanzi: "校长", pinyin: "xiàozhǎng", hskLevel: 3, meaningEn: "principal", meaningMn: "захирал", audioUrl: "/audio/xiaozhang.mp3" },
  { id: "xinwen", hanzi: "新闻", pinyin: "xīnwén", hskLevel: 3, meaningEn: "news", meaningMn: "мэдээ", audioUrl: "/audio/xinwen.mp3" },
  { id: "xinxian", hanzi: "新鲜", pinyin: "xīnxiān", hskLevel: 3, meaningEn: "fresh", meaningMn: "шинэ", audioUrl: "/audio/xinxian.mp3" },
  { id: "xinyongka", hanzi: "信用卡", pinyin: "xìnyòngkǎ", hskLevel: 3, meaningEn: "credit card", meaningMn: "зээлийн карт", audioUrl: "/audio/xinyongka.mp3" },
  { id: "xinglixiang", hanzi: "行李箱", pinyin: "xínglixiāng", hskLevel: 3, meaningEn: "suitcase", meaningMn: "аялалын цүнх", audioUrl: "/audio/xinglixiang.mp3" },
  { id: "xiongmao", hanzi: "熊猫", pinyin: "xióngmāo", hskLevel: 3, meaningEn: "panda", meaningMn: "панда", audioUrl: "/audio/xiongmao.mp3" },
  { id: "xuyao", hanzi: "需要", pinyin: "xūyào", hskLevel: 3, meaningEn: "need", meaningMn: "хэрэгтэй", audioUrl: "/audio/xuyao.mp3" },
  { id: "xuanze", hanzi: "选择", pinyin: "xuǎnzé", hskLevel: 3, meaningEn: "choose, choice", meaningMn: "сонгох", audioUrl: "/audio/xuanze.mp3" },
  { id: "yaoqiu", hanzi: "要求", pinyin: "yāoqiú", hskLevel: 3, meaningEn: "requirement, demand", meaningMn: "шаардлага", audioUrl: "/audio/yaoqiu.mp3" },
  { id: "yeye", hanzi: "爷爷", pinyin: "yéye", hskLevel: 3, meaningEn: "grandpa", meaningMn: "өвөө", audioUrl: "/audio/yeye.mp3" },
  { id: "yiding", hanzi: "一定", pinyin: "yídìng", hskLevel: 3, meaningEn: "certainly", meaningMn: "заавал, тодорхой", audioUrl: "/audio/yiding.mp3" },
  { id: "yigong", hanzi: "一共", pinyin: "yígòng", hskLevel: 3, meaningEn: "altogether", meaningMn: "нийт", audioUrl: "/audio/yigong.mp3" },
  { id: "yihuir", hanzi: "一会儿", pinyin: "yíhuìr", hskLevel: 3, meaningEn: "a while", meaningMn: "хэсэг хугацаа", audioUrl: "/audio/yihuir.mp3" },
  { id: "yiyang", hanzi: "一样", pinyin: "yíyàng", hskLevel: 3, meaningEn: "same", meaningMn: "адилхан", audioUrl: "/audio/yiyang.mp3" },
  { id: "yiqian", hanzi: "以前", pinyin: "yǐqián", hskLevel: 3, meaningEn: "before", meaningMn: "өмнө нь", audioUrl: "/audio/yiqian.mp3" },
  { id: "yiban", hanzi: "一般", pinyin: "yìbān", hskLevel: 3, meaningEn: "generally, ordinary", meaningMn: "ерөнхийдөө", audioUrl: "/audio/yiban.mp3" },
  { id: "yibian", hanzi: "一边", pinyin: "yìbiān", hskLevel: 3, meaningEn: "one side, while", meaningMn: "нэг талаас", audioUrl: "/audio/yibian.mp3" },
  { id: "yizhi", hanzi: "一直", pinyin: "yìzhí", hskLevel: 3, meaningEn: "always, straight", meaningMn: "үргэлж", audioUrl: "/audio/yizhi.mp3" },
  { id: "yinyue", hanzi: "音乐", pinyin: "yīnyuè", hskLevel: 3, meaningEn: "music", meaningMn: "хөгжим", audioUrl: "/audio/yinyue.mp3" },
  { id: "yinhang", hanzi: "银行", pinyin: "yínháng", hskLevel: 3, meaningEn: "bank", meaningMn: "банк", audioUrl: "/audio/yinhang.mp3" },
  { id: "yinliao", hanzi: "饮料", pinyin: "yǐnliào", hskLevel: 3, meaningEn: "drink, beverage", meaningMn: "ундаа", audioUrl: "/audio/yinliao.mp3" },
  { id: "yinggai", hanzi: "应该", pinyin: "yīnggāi", hskLevel: 3, meaningEn: "should", meaningMn: "ёстой", audioUrl: "/audio/yinggai.mp3" },
  { id: "yingxiang", hanzi: "影响", pinyin: "yǐngxiǎng", hskLevel: 3, meaningEn: "influence", meaningMn: "нөлөөлөх", audioUrl: "/audio/yingxiang.mp3" },
  { id: "yong", hanzi: "用", pinyin: "yòng", hskLevel: 3, meaningEn: "use", meaningMn: "хэрэглэх", audioUrl: "/audio/yong.mp3" },
  { id: "youxi", hanzi: "游戏", pinyin: "yóuxì", hskLevel: 3, meaningEn: "game", meaningMn: "тоглоом", audioUrl: "/audio/youxi.mp3" },
  { id: "youming", hanzi: "有名", pinyin: "yǒumíng", hskLevel: 3, meaningEn: "famous", meaningMn: "алдартай", audioUrl: "/audio/youming.mp3" },
  { id: "you", hanzi: "又", pinyin: "yòu", hskLevel: 3, meaningEn: "again", meaningMn: "дахин", audioUrl: "/audio/you.mp3" },
  { id: "yudao", hanzi: "遇到", pinyin: "yùdào", hskLevel: 3, meaningEn: "encounter", meaningMn: "таарах", audioUrl: "/audio/yudao.mp3" },
  { id: "yuan", hanzi: "元", pinyin: "yuán", hskLevel: 3, meaningEn: "yuan (currency)", meaningMn: "юань", audioUrl: "/audio/yuan.mp3" },
  { id: "yuanyi", hanzi: "愿意", pinyin: "yuànyì", hskLevel: 3, meaningEn: "willing", meaningMn: "хүсэх", audioUrl: "/audio/yuanyi.mp3" },
  { id: "yueliang", hanzi: "月亮", pinyin: "yuèliang", hskLevel: 3, meaningEn: "moon", meaningMn: "сар", audioUrl: "/audio/yueliang.mp3" },
  { id: "yue", hanzi: "越", pinyin: "yuè", hskLevel: 3, meaningEn: "the more", meaningMn: "улам бүр", audioUrl: "/audio/yue.mp3" },
  { id: "zhan", hanzi: "站", pinyin: "zhàn", hskLevel: 3, meaningEn: "station, stand", meaningMn: "буудал, зогсох", audioUrl: "/audio/zhan.mp3" },
  { id: "zhang", hanzi: "张", pinyin: "zhāng", hskLevel: 3, meaningEn: "(measure word for flat things)", meaningMn: "(тооны үг - хавтгай зүйл)", audioUrl: "/audio/zhang.mp3" },
  { id: "zhang-grow", hanzi: "长", pinyin: "zhǎng", hskLevel: 3, meaningEn: "grow", meaningMn: "ургах", audioUrl: "/audio/zhang2.mp3" },
  { id: "zhaoji", hanzi: "着急", pinyin: "zháojí", hskLevel: 3, meaningEn: "worry, anxious", meaningMn: "түгшүүртэй", audioUrl: "/audio/zhaoji.mp3" },
  { id: "zhaogu", hanzi: "照顾", pinyin: "zhàogù", hskLevel: 3, meaningEn: "look after", meaningMn: "асрах", audioUrl: "/audio/zhaogu.mp3" },
  { id: "zhaopian", hanzi: "照片", pinyin: "zhàopiàn", hskLevel: 3, meaningEn: "photo", meaningMn: "зураг", audioUrl: "/audio/zhaopian.mp3" },
  { id: "zhaoxiangji", hanzi: "照相机", pinyin: "zhàoxiàngjī", hskLevel: 3, meaningEn: "camera", meaningMn: "гэрэл зургийн аппарат", audioUrl: "/audio/zhaoxiangji.mp3" },
  { id: "zhi-mw", hanzi: "只", pinyin: "zhī", hskLevel: 3, meaningEn: "(measure word for animals)", meaningMn: "(тооны үг - амьтан)", audioUrl: "/audio/zhi.mp3" },
  { id: "zhi-only", hanzi: "只", pinyin: "zhǐ", hskLevel: 3, meaningEn: "only", meaningMn: "зөвхөн", audioUrl: "/audio/zhi2.mp3" },
  { id: "zhiyou-cai", hanzi: "只有……才……", pinyin: "zhǐyǒu…cái…", hskLevel: 3, meaningEn: "only if", meaningMn: "зөвхөн...бол...л болно", audioUrl: "/audio/zhiyou-cai.mp3" },
  { id: "zhongwen", hanzi: "中文", pinyin: "zhōngwén", hskLevel: 3, meaningEn: "Chinese language", meaningMn: "Хятад хэл", audioUrl: "/audio/zhongwen.mp3" },
  { id: "zhongjian", hanzi: "中间", pinyin: "zhōngjiān", hskLevel: 3, meaningEn: "middle", meaningMn: "дунд", audioUrl: "/audio/zhongjian.mp3" },
  { id: "zhongyu", hanzi: "终于", pinyin: "zhōngyú", hskLevel: 3, meaningEn: "finally", meaningMn: "эцэст нь", audioUrl: "/audio/zhongyu.mp3" },
  { id: "zhong-species", hanzi: "种", pinyin: "zhǒng", hskLevel: 3, meaningEn: "species, kind", meaningMn: "төрөл", audioUrl: "/audio/zhong.mp3" },
  { id: "zhongyao", hanzi: "重要", pinyin: "zhòngyào", hskLevel: 3, meaningEn: "important", meaningMn: "чухал", audioUrl: "/audio/zhongyao.mp3" },
  { id: "zhoumo", hanzi: "周末", pinyin: "zhōumò", hskLevel: 3, meaningEn: "weekend", meaningMn: "амралтын өдөр", audioUrl: "/audio/zhoumo.mp3" },
  { id: "zhuyao", hanzi: "主要", pinyin: "zhǔyào", hskLevel: 3, meaningEn: "main, major", meaningMn: "гол", audioUrl: "/audio/zhuyao.mp3" },
  { id: "zhuyi", hanzi: "注意", pinyin: "zhùyì", hskLevel: 3, meaningEn: "pay attention", meaningMn: "анхаарах", audioUrl: "/audio/zhuyi.mp3" },
  { id: "ziji", hanzi: "自己", pinyin: "zìjǐ", hskLevel: 3, meaningEn: "oneself", meaningMn: "өөрөө", audioUrl: "/audio/ziji.mp3" },
  { id: "zixingche", hanzi: "自行车", pinyin: "zìxíngchē", hskLevel: 3, meaningEn: "bicycle", meaningMn: "дугуй", audioUrl: "/audio/zixingche.mp3" },
  { id: "zongshi", hanzi: "总是", pinyin: "zǒngshì", hskLevel: 3, meaningEn: "always", meaningMn: "үргэлж", audioUrl: "/audio/zongshi.mp3" },
  { id: "zui", hanzi: "嘴", pinyin: "zuǐ", hskLevel: 3, meaningEn: "mouth", meaningMn: "ам", audioUrl: "/audio/zui.mp3" },
  { id: "zuihou", hanzi: "最后", pinyin: "zuìhòu", hskLevel: 3, meaningEn: "last, finally", meaningMn: "хамгийн сүүлд", audioUrl: "/audio/zuihou.mp3" },
  { id: "zuijin", hanzi: "最近", pinyin: "zuìjìn", hskLevel: 3, meaningEn: "recently", meaningMn: "саяхан", audioUrl: "/audio/zuijin.mp3" },
  { id: "zuoye", hanzi: "作业", pinyin: "zuòyè", hskLevel: 3, meaningEn: "homework", meaningMn: "гэрийн даалгавар", audioUrl: "/audio/zuoye.mp3" },
]